---


- name: "copy logrotate config"
  template:
    src: "{{ item }}"
    dest: /etc/logrotate.d/apache-tomcat
    mode: 0644
    owner: root
    group: root
  with_first_found:
    - files:
       - logrotate.conf.j2
      paths:
        - "{{ tomcat_dir_prefix }}"
        - templates

- name: "copy bin/setenv.sh"
  template: 
    src: "{{ item }}"
    dest: "{{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}/bin/setenv.sh"
    mode: 0750
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  with_first_found:
    - files:
        - "bin/setenv.sh.{{ inventory_hostname }}.j2"
        - "bin/setenv.sh.{{ ansible_distribution }}.j2"
        - "bin/setenv.sh.j2"
      paths:
        - "{{ tomcat_dir_prefix }}"
        - templates

- name: "copy extra configs"
  template:
    src: "{{ tomcat_dir_prefix }}/{{ item.src }}"
    dest: "{{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}/{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  with_items: "{{ tomcat_extra_conf }}"
  when: "item.state == 'enabled'"

- name: "remove extra libs"
  file:
    path: "{{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}/{{ item.dest }}"
    state: absent
  with_items: "{{ tomcat_extra_conf }}"
  when: "item.state != 'enabled'"

- name: "create server.xml"
  template:
    src: "{{ item }}"
    dest: "{{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}/conf/server.xml"
    mode: 0750
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  with_first_found:
    - files:
      - server_{{ tomcat_config_template }}.j2
      paths:
        -  "{{ tomcat_dir_prefix }}/conf"
        - "templates/conf"