---
- name: "create install directory"
  file:
    path: "{{tomcat_install_dir }}"
    state: directory
 
- name: "download tar.gz file"
  get_url:
    url: "{{ tomcat_download_prefix }}/{{ tomcat_list[tomcat_version]['filename'] }}"
    dest: "{{ tomcat_download_dir }}/apache-tomcat.tar.gz"
    force: yes

- name: "unpack tomcat"
  unarchive:
    src: "{{ tomcat_download_dir }}/apache-tomcat.tar.gz"
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes
    creates: "{{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}"

- name: "remove install file"
  file:
    path: "{{ tomcat_download_dir }}/apache-tomcat.tar.gz"
    state: absent

- name: "create link"
  file:
    src: "{{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}"
    dest: "{{ tomcat_install_dir }}/apache-tomcat"
    state: link

- name: "creating webapps dir"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "{{ tomcat_apps_dir }}/work"
    - "{{ tomcat_apps_dir }}/webapps"
    - "{{ tomcat_apps_dir }}/logs"
    - "{{ tomcat_apps_dir }}/temp"

- name: "copy extra libs"
  get_url:
    url: "{{ tomcat_download_prefix }}/{{ item.src }}"
    dest: "{{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}/{{ item.dest }}"
    force: yes
  with_items: "{{ tomcat_extra_libs }}"
  when: "item.state == 'enabled'"

- name: "remove extra libs"
  file:
    path: "{{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}/{{ item.dest }}"
    state: absent
  with_items: "{{ tomcat_extra_libs }}"
  when: "item.state != 'enabled'"

- name: "[tomcat] create system group"
  group:
    name: "{{ tomcat_group }}"
    system: yes
    state: present

- name: "[tomcat] create system user"
  user:
    name: "{{ tomcat_user }}"
    system: yes
    state: present
    createhome: no
    home: /opt/apache-tomcat
    group: "{{ tomcat_group }}"
    shell: /bin/false

- name: "change directory permissions"
  file:
    path: "{{ item }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ tomcat_install_dir }}/{{ tomcat_list[tomcat_version]['dirname'] }}"
    - "{{ tomcat_apps_dir }}"
